name: main branch - build, test and publish to AWS

on:
  workflow_dispatch: 
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        run: dotnet restore ./WordleEngine/src/WordleEngine/WordleEngine.csproj
      - name: Build
        run: dotnet build ./WordleEngine/src/WordleEngine/WordleEngine.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test ./WordleEngine/src/WordleEngine/WordleEngine.csproj --no-restore --verbosity normal
      - name: Zip up build output
        run: |
          mkdir output
          cp -a ./WordleEngine/src/WordleEngine/bin/Release/netcoreapp3.1/ /output/
          zip  -r WordleEngine.zip ./output
      - name: deploy to AWS
        uses: yvesgurcan/deploy-lambda-function@master
        with:
          package: WordleEngine.zip
          function-name: WordleEngine
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}